// src/components/Services/services.data.js
export const services = [
  {
    slug: "mutual-funds",
    title: "Mutual Funds",
    outcome: "Build long-term wealth with diversified portfolios matched to your risk and goals.",
    highlights: [
      "Goal-based SIPs",
      "Direct-plan selection",
      "Periodic rebalancing",
    ],
    badge: "Long-term • Diversified",
    badgeTone: "yellow",
    ctaText: "Explore plan",
  },
  {
    slug: "bonds-fixed-income",
    title: "Bonds & Fixed Income",
    outcome: "Predictable returns with credit and duration managed for stability.",
    highlights: [
      "Sovereign/AAA focus",
      "Laddering approach",
      "T+1 liquidity options",
    ],
    badge: "Capital protection • Income",
    badgeTone: "green",
    ctaText: "Explore options",
  },
  {
    slug: "insurance",
    title: "Insurance (Term & Health)",
    outcome: "Protect family and wealth from life and medical risks.",
    highlights: [
      "Sum-assured planning",
      "Premium optimization",
      "Claim assistance",
    ],
    badge: "Protection • Essential",
    badgeTone: "blue",
    ctaText: "Get a free assessment",
  },
  {
    slug: "tax-planning",
    title: "Tax Planning",
    outcome: "Reduce tax drag and optimize post-tax returns.",
    highlights: [
      "80C/80D strategy",
      "Capital gains harvesting",
      "Debt-equity impact",
    ],
    badge: "Tax-efficient",
    badgeTone: "purple",
    ctaText: "Start now",
  },
  {
    slug: "goal-planning",
    title: "Goal Planning",
    outcome: "Clear path for education, home, and retirement with timelines and contributions.",
    highlights: [
      "Inflation-adjusted targets",
      "SIP set-ups",
      "Review checkpoints",
    ],
    badge: "Goal-first",
    badgeTone: "green",
    ctaText: "Plan my goals",
  },
  {
    slug: "portfolio-review",
    title: "Portfolio Review",
    outcome: "Clean up existing investments and remove underperformers.",
    highlights: [
      "XIRR analysis",
      "Overlap check",
      "Expense ratio audit",
    ],
    badge: "Diagnostic • Cleanup",
    badgeTone: "yellow",
    ctaText: "Free review",
  },
];
